#!/usr/bin/env python3
"""Reject commit messages that carry an LLM/agent/assistant sign-off or attribution.

Used by the ``commit-msg`` git hook (see ``scripts/git-hooks/commit-msg`` and
``scripts/install-git-hooks.sh``). The policy: humans author sv0vm
commits; no "Co-Authored-By: Claude", "Generated with Claude Code",
robot-emoji signatures, or equivalent agent attributions land in the
history. (Mirrors sv0-toolchain's own hook of the same name.)

Design goals:
- **Catch sign-offs, not topics.** A subject like ``fix: Claude API client retry``
  is legitimate and must pass. We only flag *trailer-style* attribution lines
  (``Co-authored-by:``, ``Signed-off-by:``, ``Generated with/by ...``) that name
  an AI agent, plus the unambiguous robot-emoji signature.
- **Deterministic + dependency-free** so it runs identically in a hook and in CI.

Exit codes: ``0`` clean, ``1`` a banned line was found, ``2`` usage error.

Run ``python3 scripts/verify_commit_msg_no_ai_signoff.py --selftest`` to exercise
the accept/reject corpus without touching git.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

# Names/identifiers that mark a machine author when they appear in an
# attribution trailer. Kept broad on purpose (covers common assistants/agents).
AI_AGENT_PATTERN = (
    r"claude|anthropic|noreply@anthropic\.com|chatgpt|openai|gpt-?[0-9]|copilot|"
    r"cursor|codeium|gemini|bard|llama|mistral|\bllm\b|\bai\b|assistant|"
    r"language model|\bbot\b"
)

# Attribution trailers that are only banned when they name an AI agent.
_TRAILER_WITH_AGENT = re.compile(
    rf"^\s*(co-authored-by|signed-off-by|assisted-by|authored-by|committed-by)\s*:.*"
    rf"(?:{AI_AGENT_PATTERN})",
    re.IGNORECASE,
)

# "Generated with/by <AI>", "Created by <AI>", "Written by <AI>" style credits.
_GENERATED_BY_AGENT = re.compile(
    rf"\b(generated|created|written|produced|authored)\s+(with|by)\b.*"
    rf"(?:{AI_AGENT_PATTERN})",
    re.IGNORECASE,
)

# Unambiguous machine signatures — banned wherever they appear.
_ALWAYS_BANNED = [
    (re.compile(r"\U0001F916"), "robot-emoji (🤖) agent signature"),
    (re.compile(r"generated with \[?claude code", re.IGNORECASE), "Claude Code attribution"),
    (re.compile(r"\bclaude\.ai/code\b", re.IGNORECASE), "claude.ai/code attribution"),
]


def _message_body(text: str) -> str:
    """Strip trailing git comment lines (``#`` scissors block) before scanning."""
    kept: list[str] = []
    for line in text.splitlines():
        if line.startswith("#"):
            continue
        kept.append(line)
    return "\n".join(kept)


def find_violations(message: str) -> list[str]:
    """Return human-readable reasons the message is rejected (empty = clean)."""
    body = _message_body(message)
    reasons: list[str] = []
    for line in body.splitlines():
        stripped = line.strip()
        if not stripped:
            continue
        if _TRAILER_WITH_AGENT.search(line):
            reasons.append(f"AI attribution trailer: {stripped!r}")
            continue
        if _GENERATED_BY_AGENT.search(line):
            reasons.append(f"AI 'generated by' credit: {stripped!r}")
            continue
        for pat, label in _ALWAYS_BANNED:
            if pat.search(line):
                reasons.append(f"{label}: {stripped!r}")
                break
    return reasons


_ACCEPT = [
    "fix: Claude API client retry on 429",
    "feat(arith): add sign/min/max/clamp for i32",
    "docs: explain how the AI-signoff hook works\n\nNo trailer here.",
    "chore: bump anthropic-sdk dependency to 0.40",  # topic mention, not a trailer
    "Co-authored-by: Jane Doe <jane@example.com>",  # human co-author is fine
]

_REJECT = [
    "feat: x\n\nCo-Authored-By: Claude <noreply@anthropic.com>",
    "feat: x\n\n🤖 Generated with Claude Code",
    "feat: x\n\nGenerated with [Claude Code](https://claude.ai/code)",
    "feat: x\n\nSigned-off-by: GPT-4 <ai@openai.com>",
    "fix: y\n\nCo-authored-by: Copilot <copilot@github.com>",
    "fix: y\n\nAuthored by an AI assistant",
]


def _selftest() -> int:
    ok = True
    for msg in _ACCEPT:
        v = find_violations(msg)
        if v:
            ok = False
            print(f"SELFTEST FAIL (should accept): {msg!r} -> {v}", file=sys.stderr)
    for msg in _REJECT:
        if not find_violations(msg):
            ok = False
            print(f"SELFTEST FAIL (should reject): {msg!r}", file=sys.stderr)
    if ok:
        print(f"verify_commit_msg_no_ai_signoff: selftest OK "
              f"({len(_ACCEPT)} accept, {len(_REJECT)} reject)")
        return 0
    return 1


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("path", nargs="?", type=Path,
                    help="Path to commit message file (git passes .git/COMMIT_EDITMSG). "
                         "Omit to read from stdin.")
    ap.add_argument("--selftest", action="store_true",
                    help="Run the built-in accept/reject corpus and exit.")
    args = ap.parse_args(argv)

    if args.selftest:
        return _selftest()

    if args.path is not None:
        try:
            message = args.path.read_text(encoding="utf-8")
        except OSError as e:
            print(f"verify_commit_msg_no_ai_signoff: cannot read {args.path}: {e}",
                  file=sys.stderr)
            return 2
    else:
        message = sys.stdin.read()

    reasons = find_violations(message)
    if reasons:
        print("commit rejected: LLM/agent sign-off is not allowed in commit messages.",
              file=sys.stderr)
        for r in reasons:
            print(f"  - {r}", file=sys.stderr)
        print("\nRemove the attribution line(s) and re-commit. "
              "To bypass in an emergency: git commit --no-verify.", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
